services:

  currency-exchange:
    image: devraman/ms-currency-exchange-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      EUREKA.CLIENT.FETCHREGISTRY: "true"
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  currency-conversion:
    image: devraman/ms-currency-conversion-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      EUREKA.CLIENT.FETCHREGISTRY: "true"
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  api-gateway:
    image: devraman/ms-api-gateway:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      EUREKA.CLIENT.FETCHREGISTRY: "true"
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  naming-server:
    image: devraman/ms-naming-server:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:latest
    mem_reservation: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always

networks:
  currency-network: